version: 2
updates:
    -
        package-ecosystem: composer
        directory: /
        schedule:
            interval: daily
        versioning-strategy: lockfile-only
        commit-message:
            prefix: '[bump]'
