#!/bin/bash
#
# Post-dependabot hook script
# Update composer-lock.yaml file upon the composer.lock
#

yamlbin=yamltools
jsonfile=composer.lock
yamlfile=composer-lock.yaml

backup=$(mktemp)

echo "Creating a copy of the original ${yamlfile}..."
cp ${yamlfile} ${backup}

echo "Updating ${yamlfile} to match ${jsonfile} contents..."
${yamlbin} convert:json:yaml ${jsonfile} ${yamlfile}

echo "Re-integrating original comments to the ${yamlfile}..."
${yamlbin} yaml:comments:merge -w ${backup} ${yamlfile}

echo "Removing ${yamlfile} copy..."
rm -i ${backup}

echo "Applied modifications:"
git diff ${yamlfile}
