#!/bin/bash
#
# Post-dependabot hook script
# Update composer-lock.yaml file upon the composer.lock
#

yamlbin=bin/application.php
jsonfile=composer.lock
yamlfile=composer-lock.yaml

backup=lock.orig

echo "Creating a copy of the original ${yamlfile}..."
cp ${yamlfile} ${backup}

echo "Updating ${yamlfile} to match ${jsonfile} contents..."
php ${yamlbin} convert:json:yaml ${jsonfile} ${yamlfile}

echo "Re-integrating original comments to the ${yamlfile}..."
php ${yamlbin} yaml:comments:merge -w ${backup} ${yamlfile}

echo "Removing ${yamlfile} copy..."
rm -i ${backup}

echo "Applied modifications:"
git diff ${yamlfile}
